In [9]:
import pandas as pd
import numpy as numpy
df = pd.read_csv("data_wrangling_medical_2021_u6773547.csv")

In [10]:
df

,rec_id,ssn,first_name,middle_name,last_name,gender,age_at_consultation,birth_date,new_medi,medicare_number,...,email,marital_status,height,weight,bmi,blood_pressure,cholesterol_level,smoking_status,clinical_notes,consultation_timestamp
0,rec-38255,a119167529,joseph,jackson,rothstein,m,9,16/6/2005,160,1600 34634 2 3,...,nmbhiabbfr.yahoo.com,NaN,136,52,28,69,143,0,seasonal-allergies,2015-06-02t10:28+00:00
1,rec-96960,h148559060,james,m,hinnant,f,60,9/9/1955,878,8787 78232 1 2,...,james44.yahoo.com,married,174,65,21,77,203,0,glaucoma,2016-09-12t16:21+00:00
2,rec-89846,i182575302,michael,juan,whitfield,f,15,10/12/2005,893,8938 59176 1 2,...,michael49@mail.com.au,NaN,165,88,32,78,116,0,shuffling-(while-walking),2020-03-03t12:35+00:00
3,rec-85752,e141244372,bryan,lawrence,roos,f,13,15/10/2003,265,2655 78596 2 2,...,pcddkhdsnp@mail.com,NaN,148,68,31,82,186,0,depressed-mood,2016-12-06t23:57+00:00
4,rec-60433,e156698479,jack,dale,mullins,m,8,7/3/2012,798,7982 32538 1 2,...,NaN,NaN,115,22,16,74,173,0,fall,2020-05-24t17:04+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,rec-65265,f140131186,reginald,thomas,ballentine,m,56,2/4/1957,662,6621 46650 1 2,...,reginald16@mail.com,widowed,194,56,14,80,304,0,angioplasty-with-stent,2013-09-26t10:57+00:00
19996,rec-53589,g150433327,victoria,diane,goodman,f,26,16/6/1987,793,7936 65928 1 1,...,victoria12@gmail.com,married,172,92,31,72,155,1,head-cold,2013-11-10t18:09+00:00
19997,rec-64261,f193935403,mayra,j,ligon,f,50,3/6/1965,768,7686 55918 1 1,...,NaN,not-married,199,73,18,75,142,0,hypertensiom,2015-09-08t20:53+00:00
19998,rec-2147,a174082079,kisha,michael,depaulo,m,13,27/9/2003,199,1996 11945 2 2,...,NaN,NaN,140,40,20,76,146,0,orthostatic-lightheadedness,2016-01-15t08:38+00:00
19999,rec-57825,b130302016,shritha,marie,mckinney,f,66,18/5/1948,465,4653 97407 2 2,...,mckinney90@mail.com,divorced,166,135,48,72,146,0,glaucoma-eye-surgery,2014-12-16t12:46+00:00